[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
egui_file = "0.10.0"
midi-msg = "0.4.0"
midir = "0.9.1"
midly = "0.5.3"
rand = "0.8.0"
