[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apres = "0.3.4"
midi-msg = "0.4.0"
midir = "0.9.1"
midly = "0.5.3"
